import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { EventsSocketProvider } from "@/contexts/SocketProvider";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Talk For a Cause",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <EventsSocketProvider>
          <ToastContainer />
          {children}
        </EventsSocketProvider>
      </body>
    </html>
  );
}
